# Generated by Django 2.1.5 on 2019-01-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='wine_abv',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='wine_color',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='wine_varietal',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
