# Generated by Django 2.1.5 on 2019-01-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0002_auto_20190117_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
