# Generated by Django 2.1.5 on 2019-01-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wine', '0003_wine_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='wine_picture',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='winery',
            name='winery_picture',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
